name = "aptis-practice"
compatibility_date = "2024-02-01"

# D1 Database
[[d1_databases]]
binding = "DB"
database_name = "aptis_db"
database_id = "your-database-id"

# R2 Storage for audio files
[[r2_buckets]]
binding = "AUDIO_BUCKET"
bucket_name = "aptis-audio"

# KV Store for caching
[[kv_namespaces]]
binding = "CACHE"
id = "your-kv-namespace-id"

# AI Gateway configuration
[ai]
binding = "AI"

# Vector database for embeddings
[[vectorize]]
binding = "VECTORS"
index_name = "aptis_embeddings"

# Queue for async tasks
[[queues]]
binding = "TASKS"
queue_name = "aptis-tasks"

[site]
bucket = "./dist"